### ISSUE TITLE
Uptime charts

### ISSUE THREAD

**Issue by TheAlexLichter** [albionstatus/albionstatus-website#7]
Guess that this will be a heavy task. It'd be really cool to provide uptime charts for the Albion Online server. The data is available (but quite irregular, ~ 1 data point per minute).

**Comment by datatypevoid** [comment]
You already working on this? If not, I could look into implementing something.

**Comment by TheAlexLichter** [comment]
Feel free to do so @datatypevoid ☺️ 
I'm currently thinking about how to solve a [bot issue](https://github.com/manniL/albionstatus-scraper-bot/issues/4) and several other things for the future :)

**Comment by datatypevoid** [comment]
I'll branch and whip up some charts with `Vue` and `d3`, in the meantime, are we talking only showing uptime charts for the time the page has been active, or throwing together a small server--`Node` perhaps?--for tracking the data? Existing `API` that I am unaware of maybe? Just want to make sure we are on the same page, rather than ninjaing code together in silence.

**Comment by TheAlexLichter** [comment]
There is already an API that gives you statuses from a given time on. Check [the microservice](https://github.com/manniL/albionstatus-microservice/) for that :)

**Comment by TheAlexLichter** [comment]
We can use all data that the API is giving us, but something like a 24h chart would be the best I guess.

**Comment by datatypevoid** [comment]
You have been busy, nice work!

**Comment by TheAlexLichter** [comment]
Well, I just thought a little bit (really just a little) ahead :)

d3 and Vue sounds good. I'm looking forward to it ☺️

**Comment by TheAlexLichter** [comment]
@datatypevoid Any updates on it? 😃

**Comment by TheAlexLichter** [comment]
Works so far
